# 40 алгоритмов, которые должен знать каждый программист на Python
# глава 2: Структуры данных, используемые в алгоритмах
*часть конспекта в тетради, с 64 стр тут)
 - структуры данных в Python: список, кортеж, множество, словарь, DataFrame, матрица
 - Абстрактные типы данных: вектор, стек, очередь
 - иерархическая структур аданных: деревья

In [1]:
# page 61
import pandas as pd

In [2]:
df = pd.DataFrame([
    ['1','Fares',32, True ],
    ['2','Elena',23, False],
    ['3','Steven',40, True]])
df.columns= ['id','name','age','decision']
df

  id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True

In [3]:
# page 63
df.iloc[1:4,3]

1    False
2     True
Name: decision, dtype: bool

In [4]:
df.iloc[1:3, :]

  id    name  age  decision
1  2   Elena   23     False
2  3  Steven   40      True

In [5]:
df[df.age>30]

  id    name  age  decision
0  1   Fares   32      True
2  3  Steven   40      True

In [6]:
# filters
df[(df.age<35)&(df.decision==True)]

  id   name  age  decision
0  1  Fares   32      True

In [7]:
# column selection
df[['name', 'age']]

     name  age
0   Fares   32
1   Elena   23
2  Steven   40

In [8]:
# импорт библиотеки Num
import numpy as np
# создадим матрицу сод. три строки и три столбца
myMatrix = np.array([[11,12,13],[21,22,23],[31,32,33]])
print('type(myMatrix):',type(myMatrix))
myMatrix

type(myMatrix): <class 'numpy.ndarray'>

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [9]:
# транспонируем матрицу
myMatrix.transpose()

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

## Абстрактные типы данных
В широком смысле абстракция - принцип, используемый для определения сложных систем с точки зрения их общих базовых функций. Применение это йконцепции при создании структур данных приводит к появлению *абстрактных типов данных (АТД или ADT Abstract Data Type). Используя АТД, мы получаем универсальную, независимую от реализации структуру данных. Это позволяет написать более простой и чистый код алгоритма, не углубляясь в детали разработки.
### Вектор
**Вектор** - это одномерная структура для хранения данных, одна из самых популярных в Python. в Python есть 2 способа создания векторов:
 - использование списка в Python

In [10]:
# создаем список из четырех элементов
myVector = [22,33,44,55]
display(myVector)
print('type(myVector):',type(myVector))

[22, 33, 44, 55]

type(myVector): <class 'list'>

 - использование массива numpy

In [11]:
myVector = np.array([22,33,44,55])
display(myVector)
print('type(myVector):',type(myVector))

array([22, 33, 44, 55])

type(myVector): <class 'numpy.ndarray'>

In [12]:
# notes about _
a=1_000_000_000
a # 1000000000

1000000000

### Стек
*Стек* - это линейная структура данных для хранения одномерного списка. Элементы в стеке могут обрабатываться по принципу LIFO(Last-In, First-Out) FIFO(First-In, First-Out). Порядок добавления и удаления элементов определяет характер стека. Новые элементы могут добавляться и удаляться только с одного конца списка.
Операции со стеком:
 - isEmpty - возвращает true если стек пуст
 - push - добавляет новый элемент
 - pop - возвращает элемент, добавленный последним и удаляет его

Создадим класс с именем Stack, в котором опишем все операции, связанные с классом stack.
Данный код реализует стек (stack) — структуру данных, работающую по принципу LIFO (Last In, First Out — «последним пришёл, первым ушёл»).

Основные компоненты кода:
 - Класс Stack — определяет структуру стека
    - Содержит методы для работы со стеком
    - Хранит данные в списке items
 - Метод __init__ — конструктор класса
    - Инициализирует пустой список items при создании объекта
 - Метод isEmpty
    -Проверяет, пуст ли стек
    - Возвращает True, если список пуст, иначе False
- Метод push
    - Добавляет элемент в конец стека
    - Использует метод append() списка
 - Метод pop
    - Удаляет и возвращает последний элемент стека
    - Использует метод pop() списка
 - Метод peek
    - Возвращает последний элемент стека без удаления
    - Получает доступ к элементу по индексу len(self.items)-1
 - Метод size
    - Возвращает количество элементов в стеке
    - Использует функцию len()

In [13]:
class Stack:
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def push(self, item):
        self.items.append(item)
    def pop(self):
        return self.items.pop()
    def peek(self):
        return self.items[len(self.items)-1]
    def size(self):
        return(len(self.items))

In [14]:
# создаем стек с четырьмя элементами
stack = Stack()
stack.push('Red')
stack.push('Green')
stack.push('Blue')
stack.push('Yellow')
print('создали стек с четырьмя элементами:')
stack

создали стек с четырьмя элементами:

In [15]:
stack.pop()

'Yellow'

In [16]:
stack.isEmpty()

False

In [17]:
stack1 = Stack()  # создание стека
stack1.push(1)    # добавление элемента
stack1.push(2)    # добавление элемента
print(stack1.peek())  # вывод: 2
print(stack1.pop())   # вывод: 2
print(stack1.size())  # вывод: 1

2
2
1

**ВременнАя сложность стеков**

| операция  | временная сложность | 
|----------|-------|
| push   | O(1) | 
| pop    | O(1)  | 
| size  | O(1)   | 
| peek  | O(1)   | 

На практике стек часто применяется для хранения истории веб-браузеров, также выполнение операции **Undo** при работе с текстом (Undo — функция, которая позволяет отменить последнее изменение в документе, вернуть файл к предыдущему состоянию).

### Очередь
очередь хранит n элементов в одномерной структуре. Элементы добавляются и удаляются по принципу FIFO. Каждая очередь имеет начало и конец. Когда элементы удаляются из начала, операция называетя "удаление из очереди" - `dequeue`. Когда элементы добавляются в конец, операция называется "постановкой в очередь" - `enqueue`

In [18]:
class Queue(object):
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def enqueue(self, item):
        self.items.insert(0, item)
    def dequeue(self):
        return self.items.pop()
    def size(self):
        return len(self.items)

Данный код реализует очередь (queue) — структуру данных, работающую по принципу FIFO (First In, First Out — «первым пришёл, первым ушёл»).

Основные компоненты кода:
1. Класс Queue
 - Наследует от базового класса object
 - Содержит методы для работы с очередью
 - Хранит элементы в списке items
2. Метод __init__
 - Конструктор класса
 - Инициализирует пустой список items
3. Метод isEmpty
 - Проверяет, пуста ли очередь
 - Сравнивает список с пустым списком
 - Возвращает True или False
4. Метод enqueue
 - Добавляет элемент в начало очереди
 - Использует метод insert(0, item)
 - Новый элемент помещается в позицию с индексом 0
5. Метод dequeue
 - Удаляет и возвращает последний добавленный элемент
 - Использует метод pop()
 - Извлекает элемент из конца списка
6. Метод size
 - Возвращает количество элементов в очереди
 - Использует встроенную функцию len()

In [19]:
queue1 = Queue() # создание очереди
queue1.enqueue(1) # добавление элемента в начало
queue1.enqueue(2) # добавление элемента в начало
print(queue1.dequeue()) # вывод: 1 (первый добавленный элемент)
print(queue1.size()) # вывод: 1

1
1

Важно отметить, что реализация очереди через список не самая эффективная, так как вставка в начало списка требует сдвига всех элементов. Для более эффективной реализации можно использовать collections.deque

In [20]:
queue = Queue()
queue.enqueue('Red')
queue.enqueue('Green')
queue.enqueue('Blue')
queue.enqueue('Yellow')
display(queue.size())
display(queue.dequeue())
display(queue.dequeue())

4

'Red'

'Green'

### Дерево
**Дерево** - иерархическая структура данных, что делает ее особенно полезной при разработке алгоритмов. Каждое дерево имеет конечный набор узлов, так что в нем есть начальный элемент данных, называемый корнем (root), и набор узлов, соединенных между собой ветвями (branches)

Таблица 2.7
|       |       | 
|----------|-------|
| Корневой узел (Root node)  | Узел без родителя называется корневым узлом. Например, на следующей диаграмме (рис. 2.8) корневым узлом служит A. В алгоритмах корневой узел, как правило, содержит наиболее важное значение во всей древовидной структуре| 
|Уровень узла (Level of a node)|Расстояние от корневого узла называется уровнем узла.На следующей диаграмме уровень узлов D, E и F равен двум|
|Узлы-братья (Siblings nodes)|Два узла в дереве называются братьями, если они расположены на одном уровне. Например, если мы взглянем на диаграмму‚ то увидим‚ что узлы B и C являются братьями|
|Дочерний и родительский узлы (Child and parent node)|Узел F является дочерним по отношению к узлу C, если они напрямую связаны и уровень узла C меньше уровня узла F. И наоборот, узел C является родительским для узла F. Узлы C и F на следующей диаграмме демонстрируют отношения родительского и дочернего узлов|
|Степень узла (Degree of a node)|Степень узла — это количество его дочерних элементов. Например, на рис. 2.8 узел B имеет степень 2|
|Степень дерева (Degree of a tree)|Степень дерева равна максимальной степени составляющих его узлов. Дерево, представленное на диаграмме рис. 2.8, имеет степень 2|
|Поддерево (Subtree)|Поддерево — это часть дерева с выбранным узлом в качестве корневого‚ а все его дочерние элементы — это узлы дерева. На диаграмме поддерево от узла E состоит из узла E в качестве корневого и узлов G и H в качестве дочерних|
|Концевой узел (Leaf node)|Узел в дереве без дочерних элементов называется концевым. Например, на рис. 2.8 D, G, H и F — это четыре концевых узла|
|Внутренний узел (Internal node)|Любой узел, который не является ни корневым, ни концевым‚ называется внутренним. У внутреннего узла имеются по крайней мере один родительский и один дочерний узлы|


Бинарное (двоичное) дерево — это особая структура данных, где каждый узел имеет не более двух потомков.

![](images/00001.jpg)

дерево на рис 2.8 имеет 4 уровня и восемь узлов.

![](images/00002.jpg)

Дерево - одна из основных структур данных, используемых при разработке деревьев решений. Благодаря своей иерархической структуре, деревья используются в алгоритмах сетевого анализа, а также в алгоритмах поиска и сортировки, где применяется стратегия типа "разделяй и властвуй".

# Алгоритмы сортировки и поиска
рассмотрим сл. алгоритмы сортировки:
 - сортировка пузырьком bubble sort
 - сортировка вставками insertion sort
 - сортировка слиянием merge sort
 - сортировка Шелла Shell sort
 - сортировка выбором selection sort

рассмотрим сл. алгоритмы поиска:
 - линейный поиск linear search
 - бинарный поиск binary search
 - интерполяционный поиск interpolation search

📌 обмен значений переменных в Python
Данный способ обмена значений используется во всех рассматриваемых нами алгоритмах сортировки и поиска.

In [21]:
var1 = 1
var2 = 2
print('Объявление переменных var1, var2:', var1, var2)
var1, var2 = var2, var1
print('Замена значений переменных var1, var2:', var1, var2)

Объявление переменных var1, var2: 1 2
Замена значений переменных var1, var2: 2 1

### Сортировка пузырьком
Сортировка пузырьком bubble sort - самый простой и медленный алгоритм сортировки. Он спроектирован так, что наибольшее значение перемещается вправо по списку на каждой итерации цикла. При наихудшем сценарии производительность этого алгоритма равна О(n**2). Поэтому его стоит испорльзовать только для небольших наборов данных.

В основе сортировки пузырьком лежит ряд итераций, называемых проходами (passes). Для списка размера N нужно совершить N - 1  проходов. Цель первого прохода - вывести наибольшее значение в конец списка. По мере выполнения алгоритма оно будет постепенно перемещаться вправо по списку. 

В процессе сортировки значения соседних элементов сравниваются между собой попарно. Если в паре большее значение находится слева, происходит перестановка (обмен). Это продолжается до тех пор, пока мы не дойдем до конца списка. Затем начинается следующий проход. Его цель переместить следующее по величине значение на предпоследнюю позицию в списке. Последний элемент не затрагивается, поскольку уже был перемещен в нужную позицию на первой итерации.

Проходы выполняются до тех пор, пока все элементы данных не будут расположены в порядке возрастания

In [22]:
# первый проход сортировки пузырьком. код
list = [25,21,22,24,23,27,26]
lastElementIndex = len(list) - 1
print('первый проход сортировки пузырьком:')
print(0, list)

for idx in range(lastElementIndex):
    if list[idx] >list[idx + 1]:
        list[idx], list[idx+1] = list[idx+1], list[idx]
        print(idx+1,list)

первый проход сортировки пузырьком:
0 [25, 21, 22, 24, 23, 27, 26]
1 [21, 25, 22, 24, 23, 27, 26]
2 [21, 22, 25, 24, 23, 27, 26]
3 [21, 22, 24, 25, 23, 27, 26]
4 [21, 22, 24, 23, 25, 27, 26]
6 [21, 22, 24, 23, 25, 26, 27]

In [23]:
len(list)

7

In [24]:
# реализация сортировки пузырьком
def BubbleSort(list):
    lastElementIndex = len(list) - 1
    for passNo in range(lastElementIndex, 0, -1): # организует проходы по списку/ # получение последовательности чисел в обратном порядке 
        for idx in range (passNo):
            if list[idx]>list[idx+1]:
                list[idx], list[idx+1] = list[idx+1], list[idx]
    return list

In [25]:
list1 = [25,21,22,24,23,127,26]
print('ДО сортировки пузырьком:')
print(list1)
BubbleSort(list1)
print('После сортировки пузырьком:')
print(list1)

ДО сортировки пузырьком:
[25, 21, 22, 24, 23, 127, 26]
После сортировки пузырьком:
[21, 22, 23, 24, 25, 26, 127]

Анализ производительности сортировки пузырьком.

Сортировка пузырьком включает в себя два уровня циклов:
 - внешний цикл. Совокупность проходов. Например, первый проход - это первая итерация внешнего цикла.
 - внутренний цикл. оставшиеся элементы в списке сортируются до тех пор, пока наибольшее значение не окажется справа. На первом проходе будет N-1 сравнений, на втором N -2. На каждом последующем проходе количество сравнений будет уменьшаться на единицу.

Из-за двух уровней цикличности наихудшая сложность алгоритма равна О(n**2)

### Сортировка вставками
Основная идея сортировки вставками заключается в том, что на каждой итерации мы удаляем элемент из имеющейся у нас структуры данных, а затем вставляем его в нужную позицию.

На первой итерации мы сортируем два элемента данных. Затем мы расширяем выборку:берм третий элемент и находим для него позицию согласно его значению. Алгоритм выполняется до тех пор, пока все элементы не будут перемещены в правльное положение.

In [ ]:
# алгоритм сортировки вставками
def InsertionSort(list):
    for i in range(1, len(list)):
        j = i-1 # индекс предыдущего элемента
        element_next = list[i]  #  сохраняем текущий элемент для вставки
        while (list[j] > element_next) and (j >= 0): #Проверяем, больше ли предыдущий элемент текущего 
            # и Убеждаемся, что не вышли за границы списка
            list[j + 1] = list[j] #  сдвигаем больший элемент вправо
            j = j - 1 # перемещаемся к предыдущему элементу
        list[j+1] = element_next # помещаем текущий элемент на найденное место
    return list

In [32]:
list2 = [25,21,22,24,230,12,26]
print('ДО сортировки вставками:')
print(list2)
InsertionSort(list2)
print('После сортировки вставками:')
print(list2)

ДО сортировки вставками:
[25, 21, 22, 24, 230, 12, 26]
После сортировки вставками:
[12, 21, 22, 24, 25, 26, 230]

В основном цикле мы проходим по всему списку. В каждой итерации двумя соседними элементами являются list[j] (текущий элемент) и list[i] (следующий элемент)

В выражениях `(list[j] > element_next) and (j >= 0)` мы сравниваем текущий элемент со следующим

Характеристики алгоритма:
 - Временная сложность: O(n²) в худшем и среднем случаях
 - Пространственная сложность: O(1) — сортировка на месте
 - Устойчивость: алгоритм устойчив (сохраняет порядок равных элементов)
 - Эффективность: хорошо работает на небольших и частично отсортированных массивах

Преимущества:
 - Простота реализации
 - Эффективность на небольших наборах данных
 - Не требует дополнительной памяти
 - Хорошо работает с почти отсортированными данными

### Сортировка слиянием
Производительность не зависит от упорядоченности входных данных. Подобно Map Reduce и другим алгоритмам обработки больших данных, в его основе лежит стратегия "разделяй и властвуй". На этапе "разделения" алгоритм рекурсивно разбивает данные на две части до тех пор, пока размер данных не станет меньше определенного порогового занчения. На этапе слияния алгоритм объединяет данные, пока мы не получим окончательный результат. Логика на рис. 3.7

![](images/00003.jpg) ![](images/00004.jpg) <br> рис. 3.7<br>

Принцип работы
Алгоритм состоит из двух основных этапов:

1. Разделение
 - Массив рекурсивно делится пополам
 - Процесс продолжается до тех пор, пока каждый подмассив не будет содержать один элемент
2. Слияние
 - Отсортированные подмассивы объединяются в правильном порядке
 - Происходит сравнение элементов и их последовательное размещение
```
Пример работы
Рассмотрим на примере массива [38, 27, 43, 3, 9, 82, 10]:

Разделение:

[38, 27, 43, 3] и [9, 82, 10]
[38, 27] [43, 3] [9, 82] [10]
[38] [27] [43] [3] [9] [82] [10]

Слияние:

Объединяем [38] и [27] → [27, 38]
Объединяем [43] и [3] → [3, 43]
Объединяем [9] и [82] → [9, 82]

Финальное объединение
```
Временная сложность
 - O(n log n) в худшем и среднем случаях

Логарифмическое количество делений массива  
Линейное время на каждую операцию слияния  

Пространственная сложность
 - O(n) — требуется дополнительная память для временных массивов

Преимущества
 - Стабильность — сохраняет порядок равных элементов
 - Гарантированная производительность — всегда O(n log n)
 - Эффективность на больших данных
 - Параллелизуемость — хорошо подходит для параллельных вычислений

Недостатки
 - Требует дополнительной памяти
 - Менее эффективен на малых массивах из-за накладных расходов

In [35]:
def MergeSort(list):
    if len(list)>1:
        mid = len(list)//2 # split list in half
        left = list [:mid]
        right = list[mid:]
        MergeSort(left) #repeats untill lenght of each list is 1
        MergeSort(right)

        a = 0
        b = 0
        c = 0
        while a < len(left) and b <len(right):
            if left[a] < right[b]:
                list[c] = left[a]
                a = a + 1
            else:
                list[c] = right[b]
                b = b + 1
            c = c + 1
        while a < len(left):
            list[c] = left[a]
            a = a + 1
            c = c + 1
        while b < len(right):
            list[c] = right[b]
            b = b + 1
            c = c + 1
    return list

In [36]:
list3 = [44, 16, 83, 7, 67, 21, 34, 45, 10]
MergeSort(list3)

[7, 10, 16, 21, 34, 44, 45, 67, 83]

## Сортировка Шелла
В случае с полностью неотсортированным списком размера N алгоритм должен совершить N – 1 полных проходов.

Алгоритм сортировки Шелла доступным языком можно описать так:

Массив делится на подмассивы, каждый из которых состоит из элементов с определённым расстоянием между ними. Обычно это расстояние равно длине массива, делённой на 2.
Массив сортируется с помощью сортировки вставками.
После завершения сортировки промежуток уменьшается вдвое и процесс повторяется.
Этот процесс повторяется до тех пор, пока расстояние не станет равным 1, и массив будет отсортирован.
Сложность
Временная сложность алгоритма сортировки Шелла зависит от выбора шагов. В худшем случае может достигать O(n2), но обычно работает значительно быстрее. лучшая временна́я сложность достигает O(n log2 n)
Пространственная сложность — O(1), так как сортировка выполняется на месте

In [ ]:
# из поисковика
def shell_sort(data: list[int]) -> list[int]:
    last_index = len(data)
    step = len(data)//2
    while step > 0:
        for i in range(step, last_index, 1):
            j = i
            delta = j - step
            while delta >= 0 and data[delta] > data[j]:
                data[delta], data[j] = data[j], data[delta]
                j = delta
                delta = j - step
        step //= 2
    return data

In [26]:
# алгоритма сортировки Шелла выглядит 
def shellSort(list):
    distance = len(list) // 2
    while distance > 0:
        for i in range(distance, len(list)):
            temp = list[i]
            j = i
    # Сортировка подсписка для текущего значения дистанции
            while j >= distance and list[j - distance] > temp:
                list[j] = list[j - distance]
                j = j-distance
            list[j] = temp
    # Уменьшаем расстояние до следующего элемента
        distance = distance//2
    return list

In [ ]:
list = [26,17,20,11,23,21,13,18,24,14,12,22,16,15,19,25]
shellSort(list)
print("Sorted array is:\n", list)

## Линейный поиск
Просто перебор всех элементов в поисках цели. В каждой точке данных выполняется поиск совпадения. При обнаружении искомых данных, алгоритм возвращает результат и выходи из цикла. В противном случае он продолжает поиск до тех пор, пока не достигнет конца структуры данных. 

Недостаток - медленный
Преимущество - данные не нужно сортировать, как того требуют алгоритмы бинарного или интерполяционного поиска.